### ISSUE TITLE
[100FC，~10 USDT]  add a quest to gitcoin about conflux mainnet

### ISSUE THREAD

**Issue by xiaods** [conflux-dao-toc/bounty#1]
1、登录https://gitcoin.co/quests/new 创建一个测试题
2、主题相关于Conflux主链内容，素材内容参考：https://confluxnetwork.org/
3、问答题不少于5个。
4、测试题要求英文。谢谢

上线后贴出地址，立即转账。
候选人请占坑的时候提供你的地址，方便转币。

老肖赞助： 100FC
================================
1、Log on to https://gitcoin.co/quests/new to create a test question
2、The subject is related to the Conflux main chain content, material content reference: https://confluxnetwork.org/
3、No less than 5 questions.
4、The test questions require English. Thank you.

Post the address on the line and transfer the money immediately.
Candidates, please provide your address when you occupy the pit for easy coin transfer.

Lao Xiao Sponsorship: 100FC

update: 
it finished by @guanzizai288  @saketjee. thanks guys.

https://gitcoin.co/townsquare?tab=activity:288486

**Comment by xiaods** [comment]
<img width="1303" alt="截屏2020-06-02 下午12 58 35" src="https://user-images.githubusercontent.com/37678/83481484-846b5180-a4d0-11ea-9a92-d778941c2549.png">

**Comment by guanzizai288** [comment]
What are the technical highlights of CONFLUX?

**Comment by guanzizai288** [comment]
经过多次测试，已经赢得荣誉，但是点击兑换后，网页不动了。所以，无法拿到荣誉。

**Comment by xiaods** [comment]
@guanzizai288 
1、把问答题在这里贴一份，如何你没有kudo的话。方便我来发布。
2、感谢参与，请提供Conflux地址，我给你发过去**100FC**

**Comment by guanzizai288** [comment]
5个问题，已经编辑完毕，拿到荣誉后，即可提交。

**Comment by guanzizai288** [comment]
地址：0x113c5708495a737f0abd52b879306e252eda15b8

**Comment by xiaods** [comment]
麻烦把FAQ提供给我，我来自己发布QUEST

<img width="665" alt="截屏2020-06-02 下午4 20 52" src="https://user-images.githubusercontent.com/37678/83497263-cb674000-a4ec-11ea-9661-c2c1672a00f4.png">

**Comment by xiaods** [comment]
本Bounty 完结。

**Comment by guanzizai288** [comment]
1、What are the technical highlights of CONFLUX?                   Expandability Diversification Safety
2、What is the exact value of the Conflux blockchain TPS in real network testing?
3000~6000
3、Conflux inherited the design idea of bitcoin, what is the only way to gain blockchain rights?
arithmetic power
4、What is the Conflux Network's self-developed consensus algorithm?
High performance consensus algorithm for tree diagrams
5、What was the amount of Conflux's initial financing round completed in Q4 2018?
$35 million

**Comment by xiaods** [comment]
thanks

**Comment by guanzizai288** [comment]
感谢提供这次机会，让我学到了很多，谢谢。

**Comment by xiaods** [comment]
客气

**Comment by adamlaska** [comment]
![аватар](https://user-images.githubusercontent.com/33218068/83509244-ccd83e80-a4d3-11ea-9160-505580f91f4a.jpg)
